name: Analysis (macOS) - Parallel Staggered Runs # Workflow name updated

on:
  workflow_dispatch:
    inputs:
      num_runs:
        description: 'Number of times to run the encode job in parallel with staggered starts' # Description updated
        required: true
        default: '1'
        type: number 
      target_heights:
        description: 'Target resolutions (comma-separated, e.g., "720,1080")'
        required: true
        default: '1080'
        type: string
      bitrate_spec:
        description: 'Bitrate specification (e.g., "290k" or "100k-200k:10k")'
        required: true
        default: '290k'
        type: string
      preset:
        description: 'Encoding preset'
        required: true
        default: 'veryslow'
        type: choice
        options:
          - ultrafast
          - superfast
          - veryfast
          - faster
          - fast
          - medium
          - slow
          - slower
          - veryslow
      audio_bitrate:
        description: 'Audio bitrate (e.g., "64k")'
        required: true
        default: '64k'
        type: string
      audio_channels:
        description: 'Audio channels'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
      audio_compression_level:
        description: 'Opus compression level (0-10, 10 is highest quality)'
        required: true
        default: '10'
        type: choice
        options:
          - '0'
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'
          - '7'
          - '8'
          - '9'
          - '10'
      test_mode:
        description: 'Enable test mode (process only a portion of video)'
        required: false
        default: false
        type: boolean
      test_duration:
        description: 'Test duration in seconds'
        required: false
        default: '10'
        type: string
      test_start_time:
        description: 'Test start time in seconds'
        required: false
        default: '0'
        type: string

jobs:
  generate_run_indices: # Changed from generate_run_matrix
    runs-on: ubuntu-latest
    outputs:
      indices_json: ${{ steps.generate_indices.outputs.indices_json }}
    steps:
      - name: Generate run indices
        id: generate_indices
        run: |
          count=${{ github.event.inputs.num_runs }}
          if ! [[ "$count" =~ ^[0-9]+$ ]] || [ "$count" -lt 1 ]; then
            echo "Error: num_runs must be a positive integer."
            exit 1
          fi
          json_array="["
          for i in $(seq 1 $count); do
            if [ $i -ne 1 ]; then
              json_array+=","
            fi
            json_array+="$i" # Output numerical indices: [1, 2, 3, ...]
          done
          json_array+="]"
          echo "Generated JSON: $json_array"
          echo "indices_json=${json_array}" >> "$GITHUB_OUTPUT"

  encode:
    needs: generate_run_indices
    runs-on: macos-latest
    timeout-minutes: 360
    strategy:
      fail-fast: true # Consider setting to 'false' if all runs should attempt completion
      max-parallel: ${{ github.event.inputs.num_runs }} # Allow all jobs to be scheduled in parallel
      matrix:
        run_index: ${{ fromJson(needs.generate_run_indices.outputs.indices_json) }} # Use numerical index, e.g., 1, 2, 3...
    
    steps:
      - name: Calculate and apply start delay for run${{ matrix.run_index }}
        run: |
          # Calculate delay: (run_index - 1) * 30 seconds
          delay_seconds=$(( (${{ matrix.run_index }} - 1) * 30 ))
          if [ $delay_seconds -gt 0 ]; then
            echo "Run ${{ matrix.run_index }} (Index: ${{ matrix.run_index }}) starting after a calculated delay of ${delay_seconds} seconds."
            sleep $delay_seconds
          else
            echo "Run ${{ matrix.run_index }} (Index: ${{ matrix.run_index }}, first run) starting immediately."
          fi
        shell: bash

      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up workspace for run${{ matrix.run_index }}
        run: |
          echo "Starting run${{ matrix.run_index }}"
          # IMPORTANT: If macos.sh writes to fixed file names in 'encoded_videos',
          # parallel runs WILL CONFLICT. Ensure macos.sh uses CURRENT_RUN_INDEX or
          # CURRENT_RUN_INSTANCE (passed via env) to create unique output files/subdirectories.
          # For example, you might want to do: mkdir -p "encoded_videos/run${{ matrix.run_index }}"
          # and have macos.sh write into that specific subdirectory.
          mkdir -p encoded_videos
          
      - name: Save macOS script from secret
        run: |
          cat > macos.sh << 'SCRIPT_EOF'
          ${{ secrets.MACOS_ENCODER_SCRIPT2 }}
          SCRIPT_EOF
          chmod +x macos.sh
          
      - name: Configure script with workflow inputs for run${{ matrix.run_index }}
        env: 
          CURRENT_RUN_INDEX: ${{ matrix.run_index }}
          CURRENT_RUN_INSTANCE: run${{ matrix.run_index }} # For script if it expects "runX" format
        run: |
          echo "Configuring script for run${{ matrix.run_index }} (Index: ${{ matrix.run_index }}) using workflow inputs..."
          # Your macos.sh script should be designed to use CURRENT_RUN_INDEX or CURRENT_RUN_INSTANCE
          # to create unique output filenames or paths if necessary to prevent conflicts.
          # For example, by modifying a variable within macos.sh like:
          # sed -i '' "s/unique_output_id=\"\"/unique_output_id=\"_run${CURRENT_RUN_INDEX}\"/" macos.sh
          # Or by adjusting output paths to "encoded_videos/run${CURRENT_RUN_INDEX}/file.mp4"

          TARGET_HEIGHTS="${{ github.event.inputs.target_heights || '1080' }}"
          BITRATE_SPEC="${{ github.event.inputs.bitrate_spec || '290k' }}"
          PRESET="${{ github.event.inputs.preset || 'veryslow' }}"
          AUDIO_BITRATE="${{ github.event.inputs.audio_bitrate || '64k' }}"
          AUDIO_CHANNELS="${{ github.event.inputs.audio_channels || '1' }}"
          AUDIO_COMPRESSION_LEVEL="${{ github.event.inputs.audio_compression_level || '10' }}"
          TEST_MODE_BOOL="${{ github.event.inputs.test_mode }}" 
          TEST_MODE=$([[ "$TEST_MODE_BOOL" == "true" ]] && echo "1" || echo "0")
          TEST_DURATION="${{ github.event.inputs.test_duration || '10' }}"
          TEST_START_TIME="${{ github.event.inputs.test_start_time || '0' }}"
          
          HEIGHTS_ARRAY=$(echo "$TARGET_HEIGHTS" | sed 's/,/" "/g' | sed 's/^/"/' | sed 's/$/"/')
          
          sed -i '' "s/BITRATE_SPEC=\"290k\"/BITRATE_SPEC=\"$BITRATE_SPEC\"/" macos.sh
          sed -i '' "s/TARGET_HEIGHTS=(\"1080\")/TARGET_HEIGHTS=($HEIGHTS_ARRAY)/" macos.sh
          sed -i '' "s/PRESET=\"veryslow\"/PRESET=\"$PRESET\"/" macos.sh
          sed -i '' "s/AUDIO_BITRATE=\"64k\"/AUDIO_BITRATE=\"$AUDIO_BITRATE\"/" macos.sh
          sed -i '' "s/AUDIO_CHANNELS=1/AUDIO_CHANNELS=$AUDIO_CHANNELS/" macos.sh
          sed -i '' "s/AUDIO_COMPRESSION_LEVEL=10/AUDIO_COMPRESSION_LEVEL=$AUDIO_COMPRESSION_LEVEL/" macos.sh
          sed -i '' "s/TEST_MODE=0/TEST_MODE=$TEST_MODE/" macos.sh
          sed -i '' "s/TEST_DURATION=10/TEST_DURATION=$TEST_DURATION/" macos.sh
          sed -i '' "s/TEST_START_TIME=0/TEST_START_TIME=$TEST_START_TIME/" macos.sh

          echo "Script configuration complete for run${{ matrix.run_index }}."
          
      - name: Run encoder script on macOS for run${{ matrix.run_index }}
        run: |
          echo "Executing macos.sh for run${{ matrix.run_index }} (Index: ${{ matrix.run_index }})..."
          # Consider removing > /dev/null 2>&1 during testing to see output/errors
          bash macos.sh #> /dev/null 2>&1 
          echo "macos.sh execution finished for run${{ matrix.run_index }}."
          
      - name: Clean up workspace for run${{ matrix.run_index }}
        if: always()
        run: |
          echo "Cleaning up macos.sh for run${{ matrix.run_index }}"
          rm -f macos.sh
