# .github/workflows/main.yml

name: macOS Remote Environment Setup

on:
  workflow_dispatch:

jobs:
  setup-environment:
    # Use the latest macOS runner provided by GitHub
    runs-on: macos-latest
    
    steps:
    # 1. Checks out your repository's code
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # 2. Install Tailscale using Homebrew as the standard user (no sudo)
    - name: Install Tailscale
      run: brew install tailscale
      
    # 3. Safely create the configuration script from the secret
    - name: Create configuration script from secret
      run: echo "$MAC_SCRIPT" > setup.sh
      env:
        MAC_SCRIPT: ${{ secrets.MAC_SETUP_SCRIPT3 }}
        
    # 4. The script must be made executable before it can be run
    - name: Make setup script executable
      run: chmod +x setup.sh
    
    # 5. Run the configuration script with sudo, passing the auth key through
    - name: Configure and connect Tailscale
      run: sudo NETWORK_AUTH_KEY=$NETWORK_AUTH_KEY ./setup.sh
      env:
        NETWORK_AUTH_KEY: ${{ secrets.NETWORK_AUTH_KEY }}
        
    # 6. Keep the job running for remote access
    - name: Keep session active
      run: |
        echo "✅ Remote access is configured. Keeping session alive for 6 hours."
        # The total duration is 21600 seconds (6 hours).
        end_time=$((SECONDS + 21600))
        
        while [ $SECONDS -lt $end_time ]; do
          # This loop prints a message every 5 minutes (300 seconds)
          # to prevent the runner from being terminated due to inactivity.
          echo "Session is active. Will continue for another $(($((end_time - SECONDS)) / 60)) minutes."
          sleep 300
        done
        
        echo "🏁 6-hour session has ended."
