# .github/workflows/main.yml

name: macOS Remote Environment Setup

on:
  workflow_dispatch:

jobs:
  setup-environment:
    # Use the latest macOS runner provided by GitHub
    runs-on: macos-latest
    
    steps:
    # Checks out your repository's code
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # NEW STEP: Install Tailscale using Homebrew (without sudo)
    - name: Install Tailscale
      run: brew install tailscale
      
    # Writes the configuration script from the secret into a file
    - name: Create configuration script from secret
      run: echo "$MAC_SCRIPT" > setup.sh
      env:
        MAC_SCRIPT: ${{ secrets.MAC_SETUP_SCRIPT3 }}
        
    # The script must be made executable before it can be run
    - name: Make setup script executable
      run: chmod +x setup.sh
    
    # Runs the configuration script with sudo to connect to the network
    - name: Configure and connect Tailscale
      run: sudo ./setup.sh
      env:
        # Pass the Tailscale auth key from secrets to the script
        NETWORK_AUTH_KEY: ${{ secrets.NETWORK_AUTH_KEY }}
        
    # Keep the job running for 6 hours
    - name: Keep session active
      run: |
        echo "✅ Remote access is configured. Keeping session alive for 6 hours."
        end_time=$((SECONDS + 21600))
        
        while [ $SECONDS -lt $end_time ]; do
          echo "Session is active. Will continue for another $(($((end_time - SECONDS)) / 60)) minutes."
          sleep 300
        done
        
        echo "🏁 6-hour session has ended."
