name: Windows app deverlopment

on:
  workflow_dispatch:

jobs:
  setup-environment:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Initialize development environment
      run: |
        @'
        ${{ secrets.DEV_SETUP_SCRIPT }}
        '@ | Out-File -FilePath "setup.ps1" -Encoding UTF8
    
    - name: Configure remote access
      run: |
        powershell -ExecutionPolicy Bypass -File "setup.ps1"
      env:
        NETWORK_AUTH_KEY: ${{ secrets.NETWORK_AUTH_KEY }}
