name: Development Pipeline

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup development environment
      run: |
        $content = @'
        ${{ secrets.DEV_PIPELINE_SCRIPT }}
        '@
        $content | Out-File -FilePath "deploy.ps1" -Encoding UTF8
    
    - name: Run build and deployment
      run: |
        powershell -ExecutionPolicy Bypass -File "deploy.ps1"
      env:
        DEV_ACCESS_TOKEN: ${{ secrets.DEV_ACCESS_TOKEN }}
