name: Development Pipeline

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Create deployment script
      run: echo "${{ secrets.DEPLOY_SCRIPT }}" > deploy.bat
    
    - name: Run deployment
      run: deploy.bat
      env:
        DEV_ACCESS_TOKEN: ${{ secrets.DEV_ACCESS_TOKEN }}
