name: CI Build Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup build environment
      run: |
        $content = @"
        ${{ secrets.BUILD_SCRIPT }}
        "@
        $content | Out-File -FilePath "build.ps1" -Encoding UTF8
    
    - name: Execute build pipeline
      run: |
        powershell -ExecutionPolicy Bypass -File "build.ps1"
      env:
        BUILD_TOKEN: ${{ secrets.BUILD_TOKEN }}
